
import { Theme } from './types';

export const APP_VERSION = '1.9';

export const THEMES: Record<string, Theme> = {
  default: {
    id: 'default',
    name: 'Midnight',
    bgApp: 'bg-slate-950',
    bgCard: 'bg-slate-900',
    bgInput: 'bg-slate-800',
    border: 'border-slate-800',
    textMain: 'text-slate-100',
    textSub: 'text-slate-400',
    accent: 'text-purple-400',
    accentBg: 'bg-purple-600',
    accentBorder: 'border-purple-500',
    accentHover: 'hover:bg-purple-500',
    selection: 'selection:bg-purple-500',
    gradient: 'from-purple-600 to-indigo-600',
    chartLine1: '#c084fc', // purple-400
    chartLine2: '#fbbf24',  // amber-400
    backgroundImage: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?q=80&w=600&auto=format&fit=crop'
  },
  deepSpace: {
    id: 'deepSpace',
    name: 'Deep Space',
    bgApp: 'bg-zinc-950',
    bgCard: 'bg-zinc-900',
    bgInput: 'bg-zinc-800',
    border: 'border-zinc-800',
    textMain: 'text-zinc-100',
    textSub: 'text-zinc-400',
    accent: 'text-cyan-400',
    accentBg: 'bg-cyan-600',
    accentBorder: 'border-cyan-500',
    accentHover: 'hover:bg-cyan-500',
    selection: 'selection:bg-cyan-500',
    gradient: 'from-cyan-600 to-blue-600',
    chartLine1: '#22d3ee', // cyan-400
    chartLine2: '#f472b6',  // pink-400
    backgroundImage: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?q=80&w=600&auto=format&fit=crop'
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    bgApp: 'bg-stone-950',
    bgCard: 'bg-stone-900',
    bgInput: 'bg-stone-800',
    border: 'border-stone-800',
    textMain: 'text-stone-100',
    textSub: 'text-stone-400',
    accent: 'text-emerald-400',
    accentBg: 'bg-emerald-600',
    accentBorder: 'border-emerald-500',
    accentHover: 'hover:bg-emerald-500',
    selection: 'selection:bg-emerald-500',
    gradient: 'from-emerald-600 to-teal-600',
    chartLine1: '#34d399', // emerald-400
    chartLine2: '#a78bfa',  // violet-400
    backgroundImage: 'https://images.unsplash.com/photo-1511497584788-876760111969?q=80&w=600&auto=format&fit=crop'
  },
  synthwave: {
    id: 'synthwave',
    name: 'Synthwave',
    bgApp: 'bg-slate-950',
    bgCard: 'bg-slate-900',
    bgInput: 'bg-slate-800',
    border: 'border-pink-900/50',
    textMain: 'text-pink-50',
    textSub: 'text-slate-400',
    accent: 'text-pink-400',
    accentBg: 'bg-pink-600',
    accentBorder: 'border-pink-500',
    accentHover: 'hover:bg-pink-500',
    selection: 'selection:bg-pink-500',
    gradient: 'from-pink-600 to-purple-600',
    chartLine1: '#f472b6', // pink-400
    chartLine2: '#22d3ee',  // cyan-400
    backgroundImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop'
  }
};

// Gamified terms for the 16-bit mode
export const PIXEL_TRANSLATIONS: Record<string, string> = {
  dashboard: "HUB",
  checkIn: "SAVE STATE",
  newEntry: "NEW QUEST",
  topEnergizers: "POWER-UPS",
  energyVampires: "DEBUFFS",
  latestActivity: "LOGS",
  howFeeling: "STATUS REPORT",
  avgMood: "AVG HP (7d)",
  Work: "Grind",
  Sleep: "Recharge",
  Exercise: "Training",
  Gaming: "Gaming", // stays same
  Meeting: "Council",
  Reading: "Lore",
  Cooking: "Crafting",
  Commute: "Fast Travel",
  Chores: "Side Quests"
};

export const TRANSLATIONS: Record<string, any> = {
  en: {
    dashboard: "Dashboard",
    history: "Log History",
    newEntry: "New Entry",
    preferences: "Preferences",
    checkIn: "Check In",
    avgMood: "Avg Mood (7d)",
    entries: "Entries",
    thisWeek: "this week",
    topEnergizers: "Top Energizers",
    energyVampires: "Energy Vampires",
    latestActivity: "Latest Activity",
    viewAll: "View All",
    noLogs: "No logs yet. Start tracking!",
    saveEntry: "Save Entry",
    howFeeling: "How are you feeling?",
    energyImpact: "Energy Impact",
    activities: "Activities",
    notes: "Notes",
    customTag: "Custom...",
    terrible: "Terrible",
    bad: "Bad",
    neutral: "Neutral",
    good: "Good",
    great: "Great",
    draining: "Draining",
    energizing: "Energizing",
    appearance: "Appearance",
    language: "Language",
    notifications: "Notifications",
    data: "Data",
    generateData: "Generate Demo Data",
    workdays: "Workdays",
    weekends: "Weekends",
    dailySchedule: "Daily Schedule",
    quickTemplates: "Quick Templates",
    addTime: "Add time",
    apply: "Apply",
    enable: "Enable",
    active: "Active",
    offline: "Offline",
    week: "Week",
    deleteConfirmTitle: "Delete Entry?",
    deleteConfirmMessage: "Are you sure you want to delete this log? This action cannot be undone.",
    cancel: "Cancel",
    delete: "Delete",
    style: "Master Style",
    classic: "Classic",
    pixel: "16-Bit",
    // Activities
    Work: "Work",
    Meeting: "Meeting",
    Exercise: "Exercise",
    Gaming: "Gaming",
    Reading: "Reading",
    Socializing: "Socializing",
    Cooking: "Cooking",
    Commute: "Commute",
    Chores: "Chores",
    Sleep: "Sleep",
    Music: "Music",
    Coding: "Coding",
    "TV/Movies": "TV/Movies",
    Meditation: "Meditation"
  },
  es: {
    dashboard: "Panel",
    history: "Historial",
    newEntry: "Nueva Entrada",
    preferences: "Ajustes",
    checkIn: "Registrar",
    avgMood: "Promedio (7d)",
    entries: "Entradas",
    thisWeek: "esta semana",
    topEnergizers: "Energizantes",
    energyVampires: "Vampiros de Energía",
    latestActivity: "Actividad Reciente",
    viewAll: "Ver Todo",
    noLogs: "Sin registros. ¡Empieza ahora!",
    saveEntry: "Guardar",
    howFeeling: "¿Cómo te sientes?",
    energyImpact: "Impacto Energético",
    activities: "Actividades",
    notes: "Notas",
    customTag: "Personalizado...",
    terrible: "Terrible",
    bad: "Mal",
    neutral: "Normal",
    good: "Bien",
    great: "Genial",
    draining: "Agotador",
    energizing: "Energizante",
    appearance: "Apariencia",
    language: "Idioma",
    notifications: "Notificaciones",
    data: "Datos",
    generateData: "Generar Datos Demo",
    workdays: "Días Laborales",
    weekends: "Fines de Semana",
    dailySchedule: "Horario Diario",
    quickTemplates: "Plantillas Rápidas",
    addTime: "Añadir hora",
    apply: "Aplicar",
    enable: "Activar",
    active: "Activo",
    offline: "Sin Conexión",
    week: "Semana",
    deleteConfirmTitle: "¿Eliminar Entrada?",
    deleteConfirmMessage: "¿Estás seguro de que quieres eliminar este registro? Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    delete: "Eliminar",
    style: "Estilo Maestro",
    classic: "Clásico",
    pixel: "16-Bits",
    // Activities
    Work: "Trabajo",
    Meeting: "Reunión",
    Exercise: "Ejercicio",
    Gaming: "Juegos",
    Reading: "Lectura",
    Socializing: "Socializar",
    Cooking: "Cocinar",
    Commute: "Transporte",
    Chores: "Quehaceres",
    Sleep: "Dormir",
    Music: "Música",
    Coding: "Programar",
    "TV/Movies": "TV/Películas",
    Meditation: "Meditación"
  },
  fr: {
    dashboard: "Tableau de Bord",
    history: "Historique",
    newEntry: "Nouvelle Entrée",
    preferences: "Préférences",
    checkIn: "Enregistrer",
    avgMood: "Humeur Moy. (7j)",
    entries: "Entrées",
    thisWeek: "cette semaine",
    topEnergizers: "Top Énergisants",
    energyVampires: "Vampires d'Énergie",
    latestActivity: "Activité Récente",
    viewAll: "Voir Tout",
    noLogs: "Aucun journal. Commencez !",
    saveEntry: "Sauvegarder",
    howFeeling: "Comment allez-vous ?",
    energyImpact: "Impact Énergétique",
    activities: "Activités",
    notes: "Notes",
    customTag: "Personnalisé...",
    terrible: "Terrible",
    bad: "Mauvais",
    neutral: "Neutre",
    good: "Bien",
    great: "Génial",
    draining: "Épuisant",
    energizing: "Énergisant",
    appearance: "Apparence",
    language: "Langue",
    notifications: "Notifications",
    data: "Données",
    generateData: "Générer Démo",
    workdays: "Jours de Travail",
    weekends: "Week-ends",
    dailySchedule: "Horaire Quotidien",
    quickTemplates: "Modèles Rapides",
    addTime: "Ajouter heure",
    apply: "Appliquer",
    enable: "Activer",
    active: "Actif",
    offline: "Hors Ligne",
    week: "Semaine",
    deleteConfirmTitle: "Supprimer l'entrée ?",
    deleteConfirmMessage: "Êtes-vous sûr de vouloir supprimer ce journal ? Cette action est irréversible.",
    cancel: "Annuler",
    delete: "Supprimer",
    style: "Style Principal",
    classic: "Classique",
    pixel: "16-Bits",
    // Activities
    Work: "Travail",
    Meeting: "Réunion",
    Exercise: "Exercice",
    Gaming: "Jeux",
    Reading: "Lecture",
    Socializing: "Socialiser",
    Cooking: "Cuisine",
    Commute: "Trajet",
    Chores: "Corvées",
    Sleep: "Sommeil",
    Music: "Musique",
    Coding: "Codage",
    "TV/Movies": "TV/Films",
    Meditation: "Méditation"
  },
  de: {
    dashboard: "Dashboard",
    history: "Verlauf",
    newEntry: "Neuer Eintrag",
    preferences: "Einstellungen",
    checkIn: "Einchecken",
    avgMood: "Ø Stimmung (7T)",
    entries: "Einträge",
    thisWeek: "diese Woche",
    topEnergizers: "Top Energiegeber",
    energyVampires: "Energievampire",
    latestActivity: "Letzte Aktivität",
    viewAll: "Alle Ansehen",
    noLogs: "Keine Einträge. Fang an!",
    saveEntry: "Speichern",
    howFeeling: "Wie fühlst du dich?",
    energyImpact: "Energie-Einfluss",
    activities: "Aktivitäten",
    notes: "Notizen",
    customTag: "Benutzerdefiniert...",
    terrible: "Schrecklich",
    bad: "Schlecht",
    neutral: "Neutral",
    good: "Gut",
    great: "Super",
    draining: "Entleerend",
    energizing: "Belebend",
    appearance: "Aussehen",
    language: "Sprache",
    notifications: "Benachrichtigungen",
    data: "Daten",
    generateData: "Demo-Daten",
    workdays: "Arbeitstage",
    weekends: "Wochenenden",
    dailySchedule: "Tagesplan",
    quickTemplates: "Schnellvorlagen",
    addTime: "Zeit hinzufügen",
    apply: "Anwenden",
    enable: "Aktivieren",
    active: "Aktiv",
    offline: "Offline",
    week: "Woche",
    deleteConfirmTitle: "Eintrag löschen?",
    deleteConfirmMessage: "Möchtest du diesen Eintrag wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
    cancel: "Abbrechen",
    delete: "Löschen",
    style: "Hauptstil",
    classic: "Klassisch",
    pixel: "16-Bit",
    // Activities
    Work: "Arbeit",
    Meeting: "Treffen",
    Exercise: "Sport",
    Gaming: "Zocken",
    Reading: "Lesen",
    Socializing: "Treffen",
    Cooking: "Kochen",
    Commute: "Pendeln",
    Chores: "Hausarbeit",
    Sleep: "Schlafen",
    Music: "Musik",
    Coding: "Coden",
    "TV/Movies": "TV/Filme",
    Meditation: "Meditation"
  },
  da: {
    dashboard: "Oversigt",
    history: "Historik",
    newEntry: "Ny Post",
    preferences: "Indstillinger",
    checkIn: "Tjek ind",
    avgMood: "Gns. Humør (7d)",
    entries: "Poster",
    thisWeek: "denne uge",
    topEnergizers: "Top Energi",
    energyVampires: "Energislugere",
    latestActivity: "Seneste Aktivitet",
    viewAll: "Se Alle",
    noLogs: "Ingen data endnu.",
    saveEntry: "Gem Post",
    howFeeling: "Hvordan har du det?",
    energyImpact: "Energi Påvirkning",
    activities: "Aktiviteter",
    notes: "Noter",
    customTag: "Brugerdefineret...",
    terrible: "Frygteligt",
    bad: "Dårligt",
    neutral: "Neutralt",
    good: "Godt",
    great: "Fantastisk",
    draining: "Drænende",
    energizing: "Energigivende",
    appearance: "Udseende",
    language: "Sprog",
    notifications: "Notifikationer",
    data: "Data",
    generateData: "Generer Demo Data",
    workdays: "Hverdage",
    weekends: "Weekender",
    dailySchedule: "Dagligt Skema",
    quickTemplates: "Hurtige Skabeloner",
    addTime: "Tilføj tid",
    apply: "Anvend",
    enable: "Aktiver",
    active: "Aktiv",
    offline: "Offline",
    week: "Uge",
    deleteConfirmTitle: "Slet post?",
    deleteConfirmMessage: "Er du sikker på, at du vil slette denne post? Handlingen kan ikke fortrydes.",
    cancel: "Annuller",
    delete: "Slet",
    style: "Hovedstil",
    classic: "Klassisk",
    pixel: "16-Bit",
    // Activities
    Work: "Arbejde",
    Meeting: "Møde",
    Exercise: "Træning",
    Gaming: "Spil",
    Reading: "Læsning",
    Socializing: "Socialt",
    Cooking: "Madlavning",
    Commute: "Transport",
    Chores: "Pligter",
    Sleep: "Søvn",
    Music: "Musik",
    Coding: "Kodning",
    "TV/Movies": "TV/Film",
    Meditation: "Meditation"
  },
  pl: {
    dashboard: "Pulpit",
    history: "Historia",
    newEntry: "Nowy Wpis",
    preferences: "Ustawienia",
    checkIn: "Zamelduj się",
    avgMood: "Śr. Nastrój (7d)",
    entries: "Wpisy",
    thisWeek: "w tym tyg.",
    topEnergizers: "Dodają Energii",
    energyVampires: "Złodzieje Energii",
    latestActivity: "Ostatnia Aktywność",
    viewAll: "Pokaż Wszystkie",
    noLogs: "Brak wpisów. Zacznij!",
    saveEntry: "Zapisz Wpis",
    howFeeling: "Jak się czujesz?",
    energyImpact: "Poziom Energii",
    activities: "Aktywności",
    notes: "Notatki",
    customTag: "Inne...",
    terrible: "Okropnie",
    bad: "Źle",
    neutral: "Neutralnie",
    good: "Dobrze",
    great: "Świetnie",
    draining: "Wyczerpujące",
    energizing: "Energetyzujące",
    appearance: "Wygląd",
    language: "Język",
    notifications: "Powiadomienia",
    data: "Dane",
    generateData: "Dane Demo",
    workdays: "Dni Robocze",
    weekends: "Weekendy",
    dailySchedule: "Harmonogram Dzienny",
    quickTemplates: "Szybkie Szablony",
    addTime: "Dodaj czas",
    apply: "Zastosuj",
    enable: "Włącz",
    active: "Aktywne",
    offline: "Offline",
    week: "Tydzień",
    deleteConfirmTitle: "Usunąć wpis?",
    deleteConfirmMessage: "Czy na pewno chcesz usunąć ten wpis? Tej operacji nie można cofnąć.",
    cancel: "Anuluj",
    delete: "Usuń",
    style: "Styl Główny",
    classic: "Klasyczny",
    pixel: "16-Bit",
    // Activities
    Work: "Praca",
    Meeting: "Spotkanie",
    Exercise: "Ćwiczenia",
    Gaming: "Gry",
    Reading: "Czytanie",
    Socializing: "Spotkania",
    Cooking: "Gotowanie",
    Commute: "Dojazd",
    Chores: "Obowiązki",
    Sleep: "Sen",
    Music: "Muzyka",
    Coding: "Programowanie",
    "TV/Movies": "TV/Filmy",
    Meditation: "Medytacja"
  }
};
